platform :ios, ‘8.0’
use_frameworks!

target 'weijinrong' do

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'MJExtension', '~> 3.0.13'
pod 'ReactiveObjC', '~> 1.0.1'
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQKeyboardManager', '~> 4.0.6'
pod 'Masonry', '~> 1.0.2'

end